# Generated by Django 4.2.30 on 2026-08-09 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfile',
            name='created_by_agent',
            field=models.BooleanField(default=False),
        ),
    ]
